### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by ChristianDen** [digplan/time-ago#1]
Following your code examples using Node.js I get the following error indicating that the instance of object ta has no method named "ago".

    TypeError: Object function (){
    
    var o = { second: 1000, minute: 60*1000, hour: 60*1000*60, day: 24*60*1000*60, week: 7*24*60*1000*60,
			month: 30*24*60*1000*60, year: 365*24*60*1000*60 };

    global._timeago = function(nd){
       	var r = Math.round, pl = function(v, n){ return n + ' ' + v + (n>1 ? 's':'') + ' ago'},
       		ts = new Date().getTime() - new Date(nd).getTime(), ii;
    	for(i in o){
    		if(r(ts) < o[i]) return pl(ii||'m', r(ts/(o[ii]||1)))
    		ii = i;
    	}
    	return pl(i, r(ts/o[i]));
    }
    
    global._today = function(){
        var now = new Date();
        var Weekday = new Array("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday");
        var Month = new Array("January","February","March","April","May","June","July","August","September","October","November","December");
        return Weekday[now.getDay()]+", "+Month[now.getMonth()]+" "+now.getDate()+", "+now.getFullYear();
    }

    global._timefriendly = function(s){
        var t = s.match(/(\d).([a-z]*?)s?$/);
        return t[1] * eval(o[t[2]]);
    }
    } has no method 'ago'
    at Object.<anonymous> (/Users/christianschlosrich/Documents/mysite.com/lib/controllers/review.js:10:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/christianschlosrich/Documents/Sites/mysite.com/lib/controllers/index.js:7:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
Program node app.js exited with code 8

**Comment by digplan** [comment]
Fixed, please pull latest.
